version: "3.6"
services:
  fileupload:
    build: ./Fileupload
    restart: unless-stopped
    ports:
      - "1111:80"
    volumes:
      - ./Fileupload/src:/var/www/html
      - /var/www/html/upload
      - /var/www/html/secret
     
    
